%%% @author Jean Parpaillon <jean.parpaillon@free.fr>
%%% @copyright (C) 2015, Jean Parpaillon
%%% @doc
%%%
%%% @end
%%% Created :  7 Aug 2015 by Jean Parpaillon <jean.parpaillon@free.fr>

-module(econfig_utils).

-export([mktemp/1,
	 system_tmpdir/0,
	 gen/3,
	 pp_timestamp/0]).

mktemp(Template) ->
    TmpDir = system_tmpdir(),
    mktemp_(TmpDir, Template).

system_tmpdir() ->
    case erlang:system_info(system_architecture) of
	"win32" ->
	    "./tmp";
	_SysArch ->
	    "/tmp"
    end.

-spec pp_timestamp() -> string().
pp_timestamp() ->
    {{Y,M,D},{H,Min,S}} = calendar:now_to_universal_time(erlang:timestamp()),
    io_lib:format("~b-~2..0b-~2..0b ~2..0b:~2..0b:~2..0b", [Y,M,D,H,Min,S]).

-spec gen(Ecfg :: econfig_state:t(), Target :: filename:file(), Tmpl :: filename:file()) -> ok | {error, term()}.
gen(Ecfg, Target, Tmpl) ->
    case filelib:is_regular(Tmpl) of
	true ->
	    Ecfg2 = econfig_state:load(Ecfg),
	    Config = econfig_state:config(Ecfg2),
	    Bin = bbmustache:compile(bbmustache:parse_file(Tmpl), econfig_config:hash(Config)),
            write(Target, Bin);
	false ->
	    {error, {notfound, Tmpl}}
    end.

%%
%% Priv
%%
mktemp_(TmpDir, Template) ->
    TmpFile = filename:join([TmpDir, Template ++ io_lib:format(".~p", [erlang:phash2(make_ref())])]),
    case filelib:is_regular(TmpFile) of
	false -> 
	    ok = file:write_file(TmpFile, []),
	    TmpFile;
	true ->
	    mktemp_(TmpDir, Template)
    end.

write(Filename, Data) ->
    Data2 = [ "%%%\n",
	      "%%% Generated by econfig on ", pp_timestamp(), "\n"
	      "%%%\n",
	      Data ],
    file:write(Filename, Data2).
